[package]
name = "dominari"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "dominari"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
sdk = ["dep:serde"]

[dependencies]
anchor-lang = "0.26.0"
#core_ds = { path="../../../../sol-arc/programs/core-ds", features=["cpi"] }
core_ds = { git="https://github.com/JumpCrypto/sol-arc", features=["cpi"] }
registry = { path = "../registry", features = ["cpi"]}
serde = { version = "1.0.147", optional=true }
clockwork-sdk = "1.4.0"
base64 = "0.21.0"