[config]
max_players = 2
starting_cards = ["Scout", "Scout", "Scout"]

[config.gamemode.koth]
max_score = 100
score_interval_in_sec = 10
score_per_interval = 5

[[config.gamemode.koth.hill_tiles]]
x=3
y=3

[[config.gamemode.koth.hill_tiles]]
x=4
y=4

[map]
cost_per_tile = 1000

[map.mapmeta]
max_x = 8
max_y = 8

# Not every tile is defined. 
# If a tile is *not* defined, it's left as a blank tile
# If a tile *is* defined, the blank tile is overwritten

[[map.features]]
x=0
y=0
feature="Healer"

[[map.features]]
x=0
y=7
feature="Healer"

[[map.features]]
x=7
y=7
feature="Healer"

[[map.features]]
x=7
y=0
feature="Healer"
